### ISSUE TITLE
Drop PyOpenGL for ModernGL

### ISSUE THREAD

**Issue by einarf** [Contraz/demosys-py#10]
https://github.com/cprogrammer1994/ModernGL

Now that ModernGL also have a package for darwin, we should have the 3 main platforms covered.

After adding support for GLTF loading, profiling have shown that the sheer overhead from PyOpenGL is devastating on the performance for more complex things. The most prominent issues are the amount of calls to check gl errors for every single operation though the python api and the amount of time used to sanity check and resolve parameter to gl functions. This alone eats up about 50% of the total time when drawing a complex scene with 100+ nodes.

The performance penalty is also much more prominent on windows (even with better hardware) where the GLTFs Buggy scene (lego car) can  drop down to 10-15 fps with an i7/1080gtx on windows while osx  and linux can push closer to 30 fps on 5-6 year old hardware.

ModernGL also seems to approach buffers, shaders and vaos in a very similar way, so porting this over should not be too difficult.

Using MordernGL also means we can support headless rendering.

**Comment by stuaxo** [comment]
ModernGL definitely sounds better.

It seems like you can disable the error checking on pyopengl - but that doesn't help with the other factors.

http://pyopengl.sourceforge.net/documentation/opengl_diffs.html

**Comment by einarf** [comment]
Nice. I missed the error disabling. Still as you say here, we can get a lot more out of ModernGL.

**Comment by einarf** [comment]
Tested with `OpenGL.ERROR_CHECKING = False`. It definitely does wonders on windows, but less so in darwin and linux. I guess it mainly brings windows closer in performance. It's also correct as they say in the docs that PyOpenGL is slower on python 3. This is another reason for the shift to ModernGL.

**Comment by einarf** [comment]
Created a [moderngl](https://github.com/Contraz/demosys-py/tree/moderngl). It has working shaders with moderngl now at least. Moving to VAOs next.
