### ISSUE TITLE
Consider droping local/global resource path distinction

### ISSUE THREAD

**Issue by einarf** [Contraz/demosys-py#11]
Right now resource loading can be confusing.

`get_texture("texture.png")` vs `get_texture("texture.png", local=True)`

There is no guarantee `local=True` will enforce loading an effect-local resource anyway. It will be much simpler if each resource has a virtual directory and we always ask for resources using the global path.

This was changed due to effect templates and needs to be revisited. We could also reverse the logic where `local=False` is the default.

**Comment by einarf** [comment]
Revered the local resource logic. By default `local=False`. If the value is true we add the effects package name to the path. This is till a global resource path.

**Comment by stuaxo** [comment]
I haven't used this yet, but maybe it would be worth having something analogous to a PATH variable in a shell; some global list of locations that will be searched order for a resource?

**Comment by einarf** [comment]
Already there 😄 

`SHADER_DIRS', `TEXTURE_DIRS`, `SCENE_DIRS` are the `PATH` variable for those resources.
http://demosys-py.readthedocs.io/en/latest/settings.html#shader-dirs-finders

Just note that docs are a disaster now that we changed to ModerGL. WIP..
