### ISSUE TITLE
Low performance/More in-depth documentation

### ISSUE THREAD

**Issue by helgrima** [Contraz/demosys-py#18]
I cloned newest demosys-py and started modify basic cube template. Code is available:
[https://github.com/helgrima/saturday77/blob/master/bouncingcubes/effect.py](https://github.com/helgrima/saturday77/blob/master/bouncingcubes/effect.py)

I am quite sure that code is just silly, and that is why I got so low performance, like 15 fps.
Display adapter: NVIDIA GeForce GTX 950

Very same happened with version 0.4.0 also. 

I understand that documentation is going to be changed, as it seems that all effect templates had changes since yesterday. So could this be included in that documentation update as well?

**Comment by einarf** [comment]
I did some profiling. It's actually the matrix operation in python that are dreadfully slow! Drawing 100 cubes the naive way like this is probably not the way to go, but this was still very useful to look at.

I will provide an improved example shortly.

**Comment by einarf** [comment]
Faster naive version: https://github.com/Contraz/demosys-py-test/tree/master/testdemo/bouncingcubes

This one eliminates the matrix operations in the loop. I'll see if I can make an instanced example as well.

**Comment by einarf** [comment]
Modified a bit more. It seems I can draw around 1000 cubes the naive way and still get 60 fps when removing matrix operations in the loop. I think this is mostly related to `pyrr` creating new `ndarray` (numpy arrays) for each calculation causing memory allocations. That is the most devastating performance hit you have in python.

Still it's nice to see that it's possible to at least get at least 1000 draw calls at 60fps

**Comment by einarf** [comment]
Closing this as #8 covers the docs.
