### ISSUE TITLE
Scene / Object loading

### ISSUE THREAD

**Issue by stuaxo** [Contraz/demosys-py#2]
Hi,
   Thanks for demosys, I've been thinking of something along these lines for a while, but lack of real-world graphics experience has been a hindrance.

re your note on suggested scene/mesh formats, would integrating assimp be an option here ?

S

**Comment by stuaxo** [comment]
Having said that GLTF might be enough, since it's designed as an efficient format for assets on OpenGL.

https://www.khronos.org/gltf

**Comment by einarf** [comment]
Hi There

I've been using Assimp or the collada python library for this in the past. I definitely want to add more scene/mesh support. At least something very basic to start with.

Looking at GLTF.. that most certainly seems the way to go.

**Comment by einarf** [comment]
FYI: I have started looking at using GLTF and hope to push something to this repo in the near future.

**Comment by stuaxo** [comment]
Fantastic :)

**Comment by einarf** [comment]
FYI: I have been working lately on a GLTF2.0 loader. Will move that to a branch here as soon as things get a bit closer. obj loading should also be easy to add now that PyWavefront no longer depends on pyglet.

**Comment by einarf** [comment]
<img width="1111" alt="screen shot 2018-05-27 at 02 30 35" src="https://user-images.githubusercontent.com/5418180/40581348-7e8341ac-6156-11e8-8d28-eb6def29893d.png">
<img width="1258" alt="screen shot 2018-05-27 at 01 10 13" src="https://user-images.githubusercontent.com/5418180/40581352-9028b0b8-6156-11e8-8ee9-40f7d3ebacca.png">
<img width="1014" alt="screen shot 2018-05-27 at 01 16 58" src="https://user-images.githubusercontent.com/5418180/40581354-953b2f90-6156-11e8-9a95-cf0cc11a5f69.png">

**Comment by einarf** [comment]
Textures seems to work now as well. Material handling needs more work though.
<img width="516" alt="screen shot 2018-05-28 at 01 45 37" src="https://user-images.githubusercontent.com/5418180/40591966-c121c7f4-6219-11e8-8f1a-6a5cd88add53.png">
