### ISSUE TITLE
Reloading incorrect shader crashed demosys

### ISSUE THREAD

**Issue by helgrima** [Contraz/demosys-py#3]
When demosys is running and shader is modified, and syntax error is introduced reloading shader crashes demosys. I would like that demosys does not crash, but informs about syntax error in console and retains last known correct shader.

**Comment by einarf** [comment]
That makes totally sense. I had this on my mental list of issues,

**Comment by einarf** [comment]
Fixed in pull request #4

**Comment by einarf** [comment]
0.3.16 is now released with other reload improvements as well
