### ISSUE TITLE
Include glfw binaries in the project

### ISSUE THREAD

**Issue by einarf** [Contraz/demosys-py#50]
Having to install glfw to get this framework running is an additional burden we can avoid.

Should add these to a ``bin/`` directory.

pyglfw have ways to override search paths and library name: https://github.com/FlorianRhiem/pyGLFW/blob/master/glfw/library.py

**Comment by einarf** [comment]
Skipping this for now. It can get a bit hairy. We have other windows to pick from now as well that don't have any dependencies

**Comment by stuaxo** [comment]
Maybe a this could be done using WHLs in the future if it's still needed.

**Comment by einarf** [comment]
Definitly. Might revisit this some time in the future. Maybe make a separate optional ``pyGLFW-binaries`` package that can break without causing too much damage.

I made the new pyqt5 window default for now so users have something working out of the box on all platforms. Having a default window that worked out of the box was the main goal of this task. We don't want to make things difficult for the user.
