### ISSUE TITLE
Default effect for raymarching

### ISSUE THREAD

**Issue by helgrima** [Contraz/demosys-py#6]
Current default effect is great for showing basic stuff, but default effect for raymarching would be great. Something like [GLSL Sandbox](http://glslsandbox.com/).

I am willing to create that effect and do pull request.

**Comment by einarf** [comment]
That would mean supporting multiple default effects, right? That can always be solved somehow.

**Comment by helgrima** [comment]
Yes, that is what I basically mean. That user could use following command to create cube template:
`demosys-admin createeffect first_effect cube`

And create raymarching template:
`demosys-admin createeffect first_effect raymarching`

demosys-admin would in that case take three parameters(last one being new defaults to cube). Where last paramater defines which kind of template will be created(in this case raymarching).

This can be further expanded if needed. Does this kind of functionality sound reasonable or needed?

**Comment by einarf** [comment]
That sounds more than reasonable. Last parameter will be optional defaulting to some effect.

Maybe the help text for createeffect should also list out the available templates.

**Comment by helgrima** [comment]
Great if you like this! Help text and documentation can be expanded as this progress. So I start working on raymarching template?

**Comment by einarf** [comment]
Sure. This functionality should not be hard add as long as we know where to add the effects.

Maybe add a separate `effect_templates` folder that is parsed for packages. Then people can also add this folder in their own projects making their own templates or create packages with templates.

**Comment by helgrima** [comment]
That sounds reasonable for me. If I create one template for raymarching and after that we will see how it blends with other code. I am quite sure that I can finish it next week at the latest.

**Comment by einarf** [comment]
I can create the `effect_templates` directory, move the default effect in there and change the `createeffect` command. Then you can just drop new effect into the `effect_templates` directory and make a PR.

Sounds good?

**Comment by helgrima** [comment]
Sounds great! I try to manage find time next week to finish raymarching template. And then I will do pull request.

**Comment by einarf** [comment]
`effect_templates` is now added with the default `cube` effect. You and throw in stuff there. Will fix the `starteffect` management command soon.

Keep it to a flat structure. The effect package should be placed in the root of `effect_templates`.

**Comment by einarf** [comment]
Solved the first issues with effect templates here: bdd0989b164286fe853ff7ee52757e48cab3002a

It means we can load local package resources just by doing:

```python
shader = self.get_shader("default.glsl")
```
Instead of 

```python
shader = self.get_shader("cube/default.glsl")
```

If people for some reason want to load shaders outside the package, they need to use set the `local` parameter to false.

```python
shader = self.get_shader("cube/default.glsl", local=False)
```
This means you can drop the path so we don't hard code it in the effect template and it can be copied to a new effect without any worries. There's probably a way to remove the need for the `local` parameter in the future, but that is a bit more time consuming.

**Comment by einarf** [comment]
Pushed new `createeffect` command:

`demosys-admin createeffect mydemo/mycube --template cube_simple`
or
`./manage.py createeffect mydemo/mycube --template cube_simple`

Drop new effect templates in `effect_templates` and you are good to go.

**Comment by einarf** [comment]
Any progress on this? Don't hesitate to close the issue if it's unlikely this will be completed. There is also no shame in submitting a PR with incomplete code.

**Comment by helgrima** [comment]
Sorry about the delay. But in matter of fact I am right now travelling to party with demo and I am planning to use raymarching shader from that demo for this template.
