### ISSUE TITLE
Expand documentation for include basics of shaders

### ISSUE THREAD

**Issue by helgrima** [Contraz/demosys-py#7]
If issue #6 will be completed, then some shader basics would be great addition to documentation. Not anything like complete explanation how shaders work, but something which might induce democoder to gather more knowledge about shaders.

**Comment by einarf** [comment]
We are talking about basic GLSL knowledge here or specifically how they work in this project?

**Comment by helgrima** [comment]
Just basics how they work. But now when I think of it might be quite useless as information about sharers is available and quite easily adopted to this framework.
