### ISSUE TITLE
Upgrade to ModernGL 6

### ISSUE THREAD

**Issue by einarf** [Contraz/demosys-py#75]
ModernGL 6 is currently under development and testing can start right now if we build from source. Create a new branch for this and get started.

https://github.com/cprogrammer1994/ModernGL/issues/291

**Comment by cprogrammer1994** [comment]
Please list missing features. I will be able to help :)

**Comment by einarf** [comment]
We'll postpone it for this project because the day only has 24 hours. moderngl-window will take care of this for the most part.
